const paths={compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-2.5 5.5L8 16l2.5-5.5Z"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',bookmark:'<path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16l-6-4Z"/>',layers:'<path d="m12 3 10 5-10 5L2 8Zm-10 9 10 5 10-5M2 16l10 5 10-5"/>',map:'<path d="m9 18-6 3V6l6-3 6 3 6-3v15l-6 3Zm0 0V3m6 3v15"/>',sparkles:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5ZM20 2v4m-2-2h4"/>',arrow:'<path d="M20 12H4m6-6-6 6 6 6"/>',chevron:'<path d="m14 7-5 5 5 5"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>',sliders:'<path d="M4 5h9m4 0h3M4 12h3m4 0h9M4 19h11m4 0h1"/><circle cx="15" cy="5" r="2"/><circle cx="9" cy="12" r="2"/><circle cx="17" cy="19" r="2"/>',briefcase:'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V4h8v3M3 12c6 4 12 4 18 0m-9 1v3"/>',globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',edit:'<path d="m15 4 5 5M4 20l5-1L21 7l-4-4L5 15Zm-1 2h19"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Zm-4 9 3 3 5-6"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2.5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',external:'<path d="M14 3h7v7m0-7L11 13M10 3H4v17h17v-6"/>',check:'<path d="m5 12 4 4L19 6"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m2-16a3 3 0 0 1 0 6m1 4c3 0 4 2 4 5"/>'};
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.info}</svg>`}
function icons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon))}
function escapeHTML(text){return String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const demoJobs=[
 {id:'bi',title:'BI Team Lead',company:'Pagaya',category:'טכנולוגיה פיננסית · בינה עסקית',mark:'P',location:'תל אביב',region:'center',mode:'משרה מלאה',lead:'ניהול צוות',people:true,domain:'bi',source:'Greenhouse',url:'https://job-boards.greenhouse.io/pagayais/jobs/7785835003',signal:'תפקיד ניהולי עם השפעה עסקית',summary:'ניהול צוות BI, הובלת פתרונות אנליטיקה ושילוב AI בתהליכי קבלת החלטות.',requirements:['5+ שנות ניסיון בבינה עסקית או באנליטיקה','2+ שנות ניסיון בתפקיד הובלת BI או ניהול צוות','ניסיון ב־SQL, בכלי BI ובתהליכי עיבוד נתונים'],missing:'הניסיון שלך בניהול ובכלי BI עדיין לא הוגדר.',south:'המשרה בתל אביב. אפשרות לעבוד מהדרום לא אומתה.'},
 {id:'mlops',title:'MLOps Team Lead',company:'Fundamental',category:'מחקר בבינה מלאכותית · תשתיות למידת מכונה',mark:'F',location:'מרחוק · ישראל',region:'remote',mode:'עבודה מרחוק',lead:'ניהול צוות',people:true,domain:'engineering',source:'Ashby',url:'https://jobs.ashbyhq.com/fundamental/48f0baea-855c-49a1-b442-5869cd125398',signal:'אפשרות לעבוד מרחוק מישראל',summary:'הובלת צוות תשתיות למידת מכונה, מהמחקר ועד הפעלת מודלים בסביבת ייצור.',requirements:['7+ שנות ניסיון בתשתיות למידת מכונה','5+ שנות ניסיון בהובלה טכנית','ניסיון בהובלת צוותים, Python ותשתיות ענן'],missing:'נדרש לברר את הניסיון שלך בתשתיות ובהובלה טכנית.',south:'במקור מצוינת עבודה מרחוק מישראל. תדירות הגעה למשרד ותנאים נוספים דורשים בירור.'},
 {id:'group',title:'Data Science Group Lead',company:'Pagaya',category:'טכנולוגיה פיננסית · מדע הנתונים',mark:'P',location:'תל אביב',region:'center',mode:'משרה מלאה',lead:'ניהול קבוצה',people:true,domain:'science',source:'Greenhouse',url:'https://job-boards.greenhouse.io/pagayais/jobs/7667230003',signal:'ניהול קבוצה רב־תחומית',summary:'ניהול מדעני נתונים ואנליסטים, הובלת אסטרטגיה ומודלים לקבלת החלטות עסקיות.',requirements:['8+ שנות ניסיון במדע הנתונים או באנליטיקה','5+ שנות ניסיון בניהול צוותים רב־תחומיים','תואר שני או דוקטורט בתחום כמותי'],missing:'שנות הניסיון הניהולי וההשכלה שלך עדיין לא הוגדרו.',south:'המשרה בתל אביב. פעילות בדרום ואפשרות לעבוד ממנו לא אומתו.'},
 {id:'engineer',title:'Engineering Manager — Revenue Management Azure',company:'DoiT',category:'טכנולוגיות ענן · הנדסה',mark:'D',location:'מרחוק · ישראל',region:'remote',mode:'עבודה מרחוק',lead:'ניהול צוות',people:true,domain:'engineering',source:'Greenhouse',url:'https://job-boards.greenhouse.io/doitintl/jobs/7993868003',signal:'כיוון משיק: ניהול הנדסה ודאטה',summary:'תפקיד ניהולי המשלב עבודה טכנית עם הובלת מהנדסי תוכנה ונתונים.',requirements:['ניסיון בניהול צוותי הנדסה רב־תחומיים','התאמה לתפקיד המשלב ניהול ועבודה טכנית','בדיקת מלוא הדרישות במודעה המקורית'],missing:'צריך לברר אם ניהול הנדסה תואם את מרכז הכובד המקצועי שלך.',south:'במקור מצוינת עבודה מרחוק בישראל. התנאים המדויקים דורשים בירור.'},
 {id:'lead',title:'Lead Data Scientist',company:'Pagaya',category:'טכנולוגיה פיננסית · מחקר',mark:'P',location:'תל אביב',region:'center',mode:'משרה מלאה',lead:'הובלה מקצועית',people:false,domain:'science',source:'Greenhouse',url:'https://job-boards.greenhouse.io/pagayais/jobs/7720946003',signal:'הובלה מקצועית · ניהול עובדים לא אומת',summary:'הובלת מחקר וחניכת מדעני נתונים. המודעה אינה מבססת אחריות ישירה על עובדים.',requirements:['8+ שנות ניסיון בלמידת מכונה','תואר שני בתחום רלוונטי','ניסיון במודלים לנתונים טבלאיים ובהשפעה עסקית'],missing:'נדרש לברר אם הובלה מקצועית ללא ניהול ישיר מתאימה לך.',south:'המשרה בתל אביב. אפשרות לעבוד מהדרום לא אומתה.'}
];
let jobs=[];
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
let saved=new Set(read('kivun-saved',[])),tracking=read('kivun-tracking',{}),notes=read('kivun-notes',{}),prefs=read('kivun-prefs',{region:'south',experience:'',skills:''});
let view='jobs',region='all',query='',domain='all',leadership='all',installPrompt=null,lastFocus=null,greenhouseBusy=false;
const dialog=document.getElementById('dialog');
function persist(){try{localStorage.setItem('kivun-saved',JSON.stringify([...saved]));localStorage.setItem('kivun-tracking',JSON.stringify(tracking));localStorage.setItem('kivun-notes',JSON.stringify(notes));localStorage.setItem('kivun-prefs',JSON.stringify(prefs))}catch{toast('לא ניתן לשמור במכשיר כרגע. השינויים יישארו עד סגירת החלון.')}}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),3500)}
function statusOptions(current){return [['interested','מעניין אותי'],['applied','הגשתי מועמדות'],['interview','בתהליך ריאיון'],['done','התהליך הסתיים']].map(([key,text])=>`<option value="${key}" ${current===key?'selected':''}>${text}</option>`).join('')}
function mapLiveJob(item,checkedAt){const title=String(item.title||''),category=String(item.department||''),keywords=`${title} ${category}`;const leadershipType=/\b(manager|director|head|chief|vp)\b|מנהל|ראש צוות/i.test(title)?'people':/\blead\b|מוביל|הובלה/i.test(title)?'professional':'unknown';const jobDomain=/\b(bi|business intelligence)\b/i.test(keywords)?'bi':/data science|data scientist|analytics|machine learning|\bml\b|מדע הנתונים|אנליטיקה/i.test(keywords)?'science':/engineering|engineer|mlops|devops|תשתיות|הנדסה/i.test(keywords)?'engineering':null;return {...item,isLive:true,checkedAt,title,category:category||'משרה מישראל',mark:item.company==='DoiT'?'D':'P',mode:item.region==='remote'?'מרחוק לפי לוח המעסיק':'לפי פרטי המודעה',leadershipType,people:leadershipType==='people',lead:leadershipType==='people'?'כותרת ניהולית; אחריות דורשת אימות':leadershipType==='professional'?'כותרת הובלה; אחריות דורשת אימות':'אחריות ניהולית לא אומתה',domain:jobDomain,signal:'מופיעה כעת בלוח המעסיק',summary:'פרטי התפקיד המלאים מופיעים במודעה המקורית. היקף ניהול ותנאי עבודה לא הוסקו.',requirements:['יש לעיין בדרישות המלאות במודעה באתר המעסיק.'],missing:'לא בוצע ניתוח התאמה אוטומטי.',south:'המיקום מוצג כפי שפורסם בלוח המעסיק. אפשרות לעבוד מהדרום דורשת אימות.'}}
function formatPublicationDate(value){if(!value)return'תאריך הפרסום לא צוין';const date=new Date(value);return Number.isNaN(date.getTime())?'תאריך הפרסום לא צוין':new Intl.DateTimeFormat('he-IL',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Jerusalem'}).format(date)}
function card(job,index){const title=escapeHTML(job.title),company=escapeHTML(job.company),category=escapeHTML(job.category),location=escapeHTML(job.location),lead=escapeHTML(job.lead),mode=escapeHTML(job.mode),signal=escapeHTML(job.signal),summary=escapeHTML(job.summary),sourceLabel=job.isLive?'מופיעה כעת בלוח המעסיק':'נתוני הדגמה';return `<article class="job-card ${index===0?'featured':''}"><div class="job-top"><div class="company-mark ${escapeHTML(job.company.toLowerCase())}" aria-hidden="true">${escapeHTML(job.mark)}</div><div><div class="company-name" dir="ltr">${company}</div><div class="company-category">${category}</div></div><button class="icon-button save-job ${saved.has(job.id)?'saved':''}" data-save="${job.id}" aria-pressed="${saved.has(job.id)}" aria-label="${saved.has(job.id)?'ביטול שמירה':'שמירה'}: ${title}">${icon('bookmark')}</button></div><h3><button class="job-title" data-job="${job.id}">${title}</button></h3><div class="metadata"><span>${icon('pin')}${location}</span><span>${icon('users')}${lead}</span><span>${icon('clock')}${mode}</span></div><div class="publication-date">${icon('clock')}<span>תאריך פרסום: ${escapeHTML(formatPublicationDate(job.publishedAt))}</span></div><div class="fit-box">${icon('sparkles')}<div><strong>${signal}</strong><p>${summary}</p></div></div><div class="job-bottom"><span><i class="source-dot"></i>${escapeHTML(job.source)} · ${sourceLabel}</span>${view==='tracking'?`<label><span class="sr-only">סטטוס ${title}</span><select class="track-select" data-track="${job.id}">${statusOptions(tracking[job.id])}</select></label>`:`<button data-job="${job.id}">לפרטים ולהתאמה ${icon('arrow')}</button>`}</div></article>`}
function updateExternalLinks(){const role=leadership==='people'?'data analytics management roles':leadership==='professional'?'data analytics technical leadership roles':'senior data, analytics, BI or AI roles';const domainTerms={bi:'business intelligence and BI',science:'data science, analytics and machine learning',engineering:'data engineering and platform engineering'};const regionTerms={south:'Israel, preferably southern Israel and Beersheba, also central Israel',center:'Israel, preferably central Israel',all:'Israel'};const parts=[query.trim(),role,domainTerms[domain],prefs.skills.trim(),prefs.experience?`${prefs.experience} years of people-management experience`:'' ].filter(Boolean);const terms=`${parts.join(', ')}. Location preference: ${regionTerms[prefs.region]||regionTerms.all}.`;const linkedin=new URL('https://www.linkedin.com/jobs/search/');linkedin.searchParams.set('keywords',terms);linkedin.searchParams.set('location','Israel');document.getElementById('linkedin-search').href=linkedin.toString();const category=leadership==='people'?'executive-position':domain==='bi'?'bibig_data':domain==='science'?'algorithm':domain==='engineering'?'software':'executive-position';const categoryLabel={ 'executive-position':'משרות בכירות',bibig_data:'BI ו־Big Data',algorithm:'אלגוריתמים ומדע הנתונים',software:'פיתוח תוכנה והנדסה'}[category];document.getElementById('gotfriends-search').href=`https://www.gotfriends.co.il/jobslobby/${category}/#mobile-search`;document.getElementById('gotfriends-search').setAttribute('aria-label',`חיפוש ב־GotFriends: ${categoryLabel}. בחירת מיקום ומקצוע באתר`);document.getElementById('external-search-summary').textContent=`LinkedIn: ${role}; ${regionTerms[prefs.region]||regionTerms.all}${prefs.skills.trim()?`; כישורים: ${prefs.skills.trim()}`:''}. ב־GotFriends ייפתחו ${categoryLabel}; יש לבחור אזור ומקצוע באתר.`}
async function loadGreenhouseJobs(){if(greenhouseBusy)return;greenhouseBusy=true;const refreshButton=document.getElementById('refresh-jobs'),status=document.getElementById('source-status');refreshButton.disabled=true;status.textContent='בודק כעת את לוחות המעסיקים…';try{const response=await fetch('/api/jobs',{cache:'no-store'});if(!response.ok)throw new Error('Job source unavailable');const payload=await response.json();if(!Array.isArray(payload.sources))throw new Error('Invalid job source response');const available=payload.sources.filter(source=>source.ok);const failed=payload.sources.length-available.length;const checkedAt=String(payload.fetchedAt||new Date().toISOString());jobs=available.flatMap(source=>Array.isArray(source.jobs)?source.jobs.map(item=>mapLiveJob(item,checkedAt)):[]);const stamp=new Date(checkedAt).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'});status.textContent=available.length?`${jobs.length} משרות הופיעו כפתוחות בלוחות בבדיקה ${stamp}${failed?` · ${failed} לוחות לא זמינים`:''}`:'לא ניתן לאמת כרגע משרות פתוחות; לא מוצגות מודעות.';if(available.length&&jobs.length===0)status.textContent='הלוחות נבדקו; לא נמצאו כרגע משרות בישראל.'}catch{jobs=[];status.textContent='לא ניתן לאמת כרגע משרות פתוחות; לא מוצגות מודעות.'}finally{greenhouseBusy=false;refreshButton.disabled=false;render()}}
function render(){
 const labels={jobs:['משרות על הרדאר','הזדמנויות ששווה להכיר, והמידע שיעזור לך לבחור.'],saved:['המשרות ששמרת','כל האפשרויות שסימנת, במקום אחד.'],tracking:['התהליך שלך','מעניין אותך, הגשת, התקדמת. כל צעד נשמר כאן.'],south:['קרוב יותר לדרום','משרות מרחוק בישראל, לצד חברות עם פעילות בדרום.']};
 const titles={jobs:'גילוי משרות',saved:'המשרות ששמרתי',tracking:'התהליך שלי',south:'הזדמנויות בדרום'};
 document.getElementById('breadcrumb-title').textContent=titles[view];document.getElementById('list-title').textContent=labels[view][0];document.getElementById('list-subtitle').textContent=labels[view][1];
 document.querySelectorAll('[data-view]').forEach(el=>{el.classList.toggle('active',el.dataset.view===view);if(el.dataset.view===view)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});
 document.querySelectorAll('[data-region]').forEach(el=>{const on=el.dataset.region===region;el.classList.toggle('selected',on);el.setAttribute('aria-pressed',on)});
 const filtered=jobs.filter(job=>(view!=='saved'||saved.has(job.id))&&(view!=='tracking'||tracking[job.id])&&(view!=='south'||job.region==='remote'||job.region==='south')&&(region==='all'||job.region===region)&&(domain==='all'||job.domain===domain)&&(leadership==='all'||(job.isLive?job.leadershipType===leadership:(leadership==='people'?job.people:!job.people)))&&`${job.title} ${job.company} ${job.category} ${job.summary}`.toLowerCase().includes(query.toLowerCase()));
 document.getElementById('result-count').textContent=`${filtered.length} משרות`;
 let prefix=view==='south'?'<div class="view-intro"><strong>חיפוש משרות בדרום ומרחוק.</strong><p>המיקום ותנאי העבודה מוצגים כפי שפורסמו בלוח המעסיק; אפשרות לעבוד מהדרום דורשת אימות במודעה.</p><button class="text-button" data-action="south">חברות עם פעילות בדרום '+icon('arrow')+'</button></div>':'';
 const emptyTitle=view==='saved'?'אין משרות פתוחות שמורות כרגע':view==='tracking'?'אין כרגע משרות פעילות בתהליך המעקב':region==='south'?'לא נמצאו כרגע משרות בדרום':'לא נמצאו כרגע משרות פעילות בסינון הזה';
 const emptyText=view==='saved'?'משרות שמוסרות מלוחות המעסיקים לא יוצגו עוד כאן.':view==='tracking'?'משרות יופיעו כאן שוב רק אם יאומתו כפעילות בבדיקה עדכנית.':region==='south'?'אפשר לבדוק משרות מרחוק בישראל או לרענן את מקורות המשרות.':'אפשר לשנות את החיפוש, או לרענן את מקורות המשרות.';
 document.getElementById('job-list').innerHTML=prefix+(filtered.length?filtered.map(card).join(''):`<div class="empty">${icon(region==='south'?'sun':'search')}<h3>${emptyTitle}</h3><p>${emptyText}</p><button class="button outlined" data-action="${region==='south'?'remote':'reset'}">${region==='south'?'הצגת משרות מרחוק':'לכל המשרות'}</button></div>`);
 const liveSaved=jobs.filter(job=>saved.has(job.id)).length,liveTracking=jobs.filter(job=>tracking[job.id]).length;document.getElementById('jobs-count').textContent=jobs.length;document.getElementById('jobs-total').textContent=jobs.length;document.getElementById('remote-count').textContent=jobs.filter(job=>job.region==='remote').length;document.getElementById('saved-count').textContent=liveSaved;document.getElementById('stat-saved').textContent=String(liveSaved).padStart(2,'0');document.getElementById('tracking-count').textContent=liveTracking;
 document.getElementById('preference-summary').textContent=prefs.region==='south'?'דרום ומרכז · עדיפות לדרום':prefs.region==='center'?'דרום ומרכז · עדיפות למרכז':'דרום ומרכז · ללא עדיפות';
}
function setView(next){view=next;query='';region='all';domain='all';leadership='all';document.getElementById('search').value='';document.getElementById('domain').value='all';document.getElementById('leadership').value='all';if(location.hash!==`#${next}`)location.hash=next;render()}
function openDialog(title,body){lastFocus=document.activeElement;document.getElementById('dialog-body').innerHTML=`<div class="dialog-head"><h2>${title}</h2><button class="icon-button" data-action="close" aria-label="סגירת החלון">${icon('close')}</button></div><div class="dialog-content">${body}</div>`;if(!dialog.open)dialog.showModal()}
dialog.addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus()});dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()}});
function showJob(id){const job=jobs.find(item=>item.id===id);if(!job)return;const checkedAt=job.checkedAt?new Date(job.checkedAt).toLocaleString('he-IL'):'לא זמין';openDialog('מבט מקרוב על המשרה',`<div class="company-name" dir="ltr">${escapeHTML(job.company)}</div><h3 class="job-title">${escapeHTML(job.title)}</h3><div class="metadata"><span>${icon('pin')}${escapeHTML(job.location)}</span><span>${icon('users')}${escapeHTML(job.lead)}</span></div><p>${escapeHTML(job.summary)}</p><div class="fit-box">${icon('sparkles')}<div><strong>התאמה אישית: לא נבדקה</strong><p>לא בוצע ניתוח התאמה אוטומטי. יש לבדוק את דרישות המשרה בפרסום המקורי.</p></div></div><h3>מידע מהמקור</h3><ul><li>${escapeHTML(job.category)}</li><li>פורסמה: ${escapeHTML(formatPublicationDate(job.publishedAt))}</li><li>עודכנה על ידי המעסיק: ${escapeHTML(job.updatedAt||'לא צוין')}</li><li>נבדקה מול הלוח הפעיל: ${escapeHTML(checkedAt)}</li></ul><h3>מיקום ותנאי עבודה</h3><p>${escapeHTML(job.south)}</p><div class="dialog-form"><label>הערה לעצמי<textarea id="job-note" placeholder="מה מעניין אותי? מה כדאי לברר?">${escapeHTML(notes[id]||'')}</textarea></label><button class="text-button" data-note="${id}">שמירת ההערה ${icon('check')}</button></div><div class="dialog-actions"><a class="button primary" href="${escapeHTML(job.url)}" target="_blank" rel="noopener noreferrer">בדיקה באתר המעסיק ${icon('external')}</a><button class="button outlined" data-add-track="${id}">${tracking[id]?'המשרה בתהליך שלי':'הוספה לתהליך שלי'}</button></div><p style="font-size:11px;margin-bottom:0">המשרה הופיעה כפתוחה בלוח Greenhouse בזמן הבדיקה. הסטטוס עשוי להשתנות לאחר מכן; יש לאמת שוב באתר המעסיק. המעבר למקור אינו שולח מועמדות.</p>`)}
function preferences(){openDialog('מה חשוב לך בתפקיד הבא?',`<p>פרטים קטנים שעוזרים למצוא כיוון. ההעדפות נשמרות במכשיר הזה.</p><form id="preferences-form" class="dialog-form"><label>עדיפות גאוגרפית<select name="region"><option value="south" ${prefs.region==='south'?'selected':''}>דרום ומרכז, עם עדיפות לדרום</option><option value="center" ${prefs.region==='center'?'selected':''}>דרום ומרכז, עם עדיפות למרכז</option><option value="all" ${prefs.region==='all'?'selected':''}>דרום ומרכז, ללא עדיפות</option></select></label><label>שנות ניסיון בניהול עובדים<input name="experience" type="number" min="0" max="60" step="1" value="${escapeHTML(prefs.experience)}" placeholder="עדיין לא הוגדר"><small>בנפרד מעשר שנות הניסיון המקצועי ומעלה.</small></label><label>כישורים ומרכז הכובד המקצועי<textarea name="skills" placeholder="למשל: ניהול אנליטיקה, אסטרטגיית דאטה, הובלת מחקר…">${escapeHTML(prefs.skills)}</textarea></label><small>ההעדפות יישמרו לפרופיל. ניתוח התאמה אוטומטי יתווסף לאחר חיבור למודל.</small><div class="dialog-actions"><button class="button primary" type="submit">שמירת ההעדפות ${icon('check')}</button><button class="button outlined" type="button" data-action="close">ביטול</button></div></form>`)}
function south(){openDialog('חברות עם כיוון דרומי',`<p>נקודת התחלה לחיפוש. נוכחות בדרום אינה מבטיחה שהתפקיד המסוים מאפשר לעבוד משם.</p>${[['Microsoft','אתר באר שבע מופיע באתר מרכז הפיתוח.','https://www.microsoftrnd.co.il/whoweare','M'],['Wix','באר שבע מופיעה בין מיקומי החברה.','https://careers.wix.com/','W'],['גב־ים נגב','לוח מקומי להיכרות עם חברות ומשרות בפארק.','https://careers.gavyam-negev.co.il/','ג'],['SouthUp','חברות ופעילות טכנולוגית בנגב המערבי.','https://southup.org/he/','S']].map(([name,desc,url,mark])=>`<div class="company-row"><span class="company-mark" aria-hidden="true">${mark}</span><div><strong>${name}</strong><p>${desc}</p></div><a href="${url}" target="_blank" rel="noopener noreferrer" aria-label="מקור למידע על ${name}">למקור ${icon('external')}</a></div>`).join('')}<p style="font-size:11px">המידע מבוסס על המחקר מ־5.10.2026. אפשרות העבודה מהאתר הדרומי דורשת אימות לכל משרה בנפרד.</p><button class="button primary" data-action="south-view">משרות מרחוק בישראל ${icon('arrow')}</button>`)}
document.addEventListener('click',async event=>{const el=event.target.closest('button,a');if(!el)return;
 if(el.dataset.save){const id=el.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);persist();render();document.querySelector(`[data-save="${id}"]`)?.focus();toast(saved.has(id)?'המשרה נשמרה. היא מחכה לך במשרות ששמרתי.':'המשרה הוסרה מהמשרות ששמרתי.');return}
 if(el.dataset.job){showJob(el.dataset.job);return}
 if(el.dataset.note){notes[el.dataset.note]=document.getElementById('job-note').value;persist();toast('ההערה נשמרה במכשיר.');return}
 if(el.dataset.addTrack){if(tracking[el.dataset.addTrack]){dialog.close();setView('tracking')}else{tracking[el.dataset.addTrack]='interested';persist();render();el.textContent='המשרה בתהליך שלי';toast('נוספה לתהליך שלך. לא נשלחה מועמדות.')}return}
 if(el.dataset.view){event.preventDefault();setView(el.dataset.view);return}
 if(el.dataset.region){region=el.dataset.region;render();return}
 switch(el.dataset.action){case 'close':dialog.close();break;case 'preferences':preferences();break;case 'south':south();break;case 'south-view':dialog.close();setView('south');break;case 'saved':setView('saved');break;case 'reset':setView('jobs');break;case 'remote':setView('jobs');region='remote';render();break;case 'about':openDialog('ברוכים הבאים לכיוון',`<p>אפשר לחפש ולשמור משרות ולנהל תהליך אישי. השמירה מתבצעת במכשיר שלך.</p><p>משרות מוצגות כאן רק לאחר שהתקבלו בבדיקה עדכנית מלוחות Greenhouse פעילים. LinkedIn ו־GotFriends נפתחים לחיפוש באתר שלהם; המשרות מהם אינן מיובאות לרשימה.</p><p>התחברות, מסד נתונים מרכזי וניתוח התאמה אוטומטי עדיין אינם מחוברים.</p><button class="button primary" data-action="close">הבנתי, ממשיכים</button>`);break;case 'install':if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else{openDialog('כיוון, במרחק לחיצה',`<p>בדפדפן שתומך בהתקנה אפשר לבחור ״התקנת אפליקציה״ או ״הוספה למסך הבית״ מתפריט הדפדפן.</p><p>אם האפשרות אינה מופיעה בתצוגה המשולבת, פתחו את הכתובת בדפדפן רגיל. לאחר הביקור הראשון אפשר גם לעיין בממשק ללא רשת.</p><button class="button primary" data-action="close">הבנתי</button>`)}break}
});
document.addEventListener('change',event=>{if(event.target.dataset.track){tracking[event.target.dataset.track]=event.target.value;persist();toast('הסטטוס עודכן.')}});
document.addEventListener('submit',event=>{if(event.target.id==='preferences-form'){event.preventDefault();const data=new FormData(event.target);prefs={region:data.get('region'),experience:data.get('experience'),skills:data.get('skills')};persist();updateExternalLinks();render();dialog.close();toast('העדפות החיפוש נשמרו.')}});
document.getElementById('search').addEventListener('input',event=>{query=event.target.value;updateExternalLinks();render()});document.getElementById('domain').addEventListener('change',event=>{domain=event.target.value;updateExternalLinks();render()});document.getElementById('leadership').addEventListener('change',event=>{leadership=event.target.value;updateExternalLinks();render()});document.querySelectorAll('[data-region]').forEach(button=>button.addEventListener('click',()=>updateExternalLinks()));document.getElementById('refresh-jobs').addEventListener('click',loadGreenhouseJobs);
document.getElementById('filter-toggle').addEventListener('click',event=>{const button=event.currentTarget;const expanded=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',!expanded);document.getElementById('extra-filters').hidden=expanded});
document.addEventListener('keydown',event=>{if(event.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!dialog.open){event.preventDefault();document.getElementById('search').focus()}});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(['jobs','saved','tracking','south'].includes(next)&&next!==view)setView(next)});window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event});
function connectivity(){document.getElementById('offline').hidden=navigator.onLine}window.addEventListener('online',connectivity);window.addEventListener('offline',connectivity);
icons();const initial=location.hash.slice(1);if(['jobs','saved','tracking','south'].includes(initial))view=initial;updateExternalLinks();render();connectivity();loadGreenhouseJobs();
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
